version: 3
endpoint: https://s2rdev.hasura.app
admin_secret: ysaMH1kjRlVsUPGnJD5IXy2PZpjlGnpFumpdLCZitMCngDhe5Z064a5c6FxxL87S
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
